"""Curated word -> clue bank for the mini crossword. Common words only, British
spelling and a British slant where it's natural. Every word a grid can use must have a
clue here, so a generated puzzle is fully clued by construction."""

W5 = {
 "ABOUT":"Roughly, approximately","ABOVE":"Higher than","ACORN":"Oak's seed","ACTOR":"One treading the boards",
 "ADMIT":"Confess to","ADOPT":"Take on as your own","AGENT":"Spy, or a star's representative","AGREE":"See eye to eye",
 "ALARM":"What wakes you up","ALBUM":"Collection of tracks","ALERT":"On the ball","ALIVE":"Not dead",
 "ALLEY":"Narrow lane between buildings","ALONE":"By oneself","ALTER":"Change","AMBER":"Middle traffic light",
 "ANGEL":"Winged heavenly being","ANGER":"Rage","ANGLE":"Corner measurement","ANKLE":"Joint above the foot",
 "APPLE":"Newton's falling fruit","APRIL":"Month of showers","APRON":"Cook's cover-up","ARENA":"Sports venue",
 "ARGUE":"Have a row","ARISE":"Get up","ARMED":"Carrying weapons","AROMA":"Pleasant smell","ARROW":"Archer's ammunition",
 "ASIDE":"To one side; a stage whisper","ASSET":"Something valuable you own","AVOID":"Steer clear of",
 "AWARD":"Prize","AWARE":"Conscious of","BACON":"Full English staple","BADGE":"Pinned-on emblem",
 "BADLY":"Not well","BAKER":"One who makes bread","BASIC":"Fundamental","BASIL":"Herb for pesto",
 "BEACH":"Sandy shore","BEARD":"Facial hair","BEAST":"Wild animal","BEGAN":"Started","BEGIN":"Make a start",
 "BELOW":"Underneath","BENCH":"Park seat","BERRY":"Small soft fruit","BIRTH":"Coming into the world",
 "BLACK":"Colour of coal","BLADE":"Knife's cutting edge","BLAME":"Point the finger at","BLANK":"Empty; unfilled",
 "BLAST":"Explosion","BLEAK":"Grim and cheerless","BLEND":"Mix together","BLIND":"Unable to see",
 "BLOCK":"Obstruct","BLOOD":"What runs in your veins","BLOOM":"Flower, or flourish","BOARD":"Get on a plane",
 "BOAST":"Show off verbally","BONUS":"Extra payment","BOOST":"Give a lift to","BOOTH":"Small enclosed cubicle",
 "BOUND":"Tied up; or a leap","BRAIN":"Thinking organ","BRAKE":"Car's stopper","BRAND":"Maker's name",
 "BRASS":"Trumpet's metal","BRAVE":"Courageous","BREAD":"Loaf","BREAK":"Snap in two","BRICK":"Builder's block",
 "BRIDE":"Woman at a wedding","BRIEF":"Short","BRING":"Fetch along","BROAD":"Wide","BROWN":"Colour of soil",
 "BRUSH":"Painter's tool","BUILD":"Construct","BUNCH":"Cluster, as of grapes","BURNT":"Left too long in the oven",
 "CABIN":"Log hut","CABLE":"Thick wire","CANAL":"Man-made waterway","CANDY":"American sweets",
 "CARGO":"Ship's load","CARRY":"Transport by hand","CARVE":"Cut the Sunday joint","CATCH":"Grab in flight",
 "CAUSE":"Reason for something","CEASE":"Stop","CHAIN":"Linked metal loops","CHAIR":"Seat with a back",
 "CHALK":"Cliffs of Dover material","CHARM":"Winning appeal","CHART":"Graph; or the top 40","CHASE":"Pursue",
 "CHEAP":"Low in price","CHEAT":"Play unfairly","CHECK":"Verify","CHEEK":"Side of the face; or nerve",
 "CHESS":"Game of kings and pawns","CHEST":"Torso; or a treasure box","CHIEF":"Head honcho","CHILD":"Youngster",
 "CHILL":"Cool down","CHOIR":"Group of singers","CHOSE":"Picked","CIVIC":"To do with a city","CLAIM":"Assert as true",
 "CLASS":"School group","CLEAN":"Spotless","CLEAR":"Easy to see through","CLERK":"Office worker",
 "CLICK":"Mouse sound","CLIFF":"Steep rock face","CLIMB":"Go up","CLOCK":"Timepiece on the wall",
 "CLOSE":"Shut","CLOTH":"Fabric","CLOUD":"Sky's fluffy white thing","COACH":"Team's trainer; or a bus",
 "COAST":"Where land meets sea","COLON":"Punctuation before a list","COLOUR":"","COMET":"Icy visitor with a tail",
 "COMIC":"Funny; or a picture magazine","CORAL":"Reef builder","COUCH":"Sofa","COUGH":"Chesty splutter",
 "COUNT":"Tally up","COURT":"Where a case is heard","COVER":"Put a lid on","CRACK":"Thin split",
 "CRAFT":"Skilled trade","CRANE":"Building site lifter; or a wading bird","CRASH":"Collide",
 "CRAWL":"Move on all fours","CRAZY":"Barking mad","CREAM":"Top of the milk","CREEK":"Small stream",
 "CREPT":"Moved stealthily","CRIME":"Unlawful act","CROSS":"Annoyed; or an X","CROWD":"Throng",
 "CROWN":"Monarch's headgear","CRUEL":"Deliberately unkind","CRUSH":"Squash flat","CURVE":"Bend in the road",
 "CYCLE":"Ride a bike","DAILY":"Every day","DAIRY":"Milk and cheese aisle","DANCE":"Move to music",
 "DATED":"Old-fashioned","DEALT":"Handed out the cards","DEATH":"The end","DEBUT":"First appearance",
 "DECAY":"Rot","DELAY":"Hold up","DEPTH":"How deep something is","DEVIL":"Old Nick","DIARY":"Daily journal",
 "DIRTY":"Grubby","DITCH":"Roadside trench; or abandon","DIZZY":"Head spinning","DOING":"Carrying out",
 "DOUBT":"Uncertainty","DOZEN":"Twelve","DRAFT":"Rough first version","DRAIN":"Where the water goes",
 "DRAMA":"Theatre genre","DRANK":"Downed","DREAM":"What happens while asleep","DRESS":"Frock",
 "DRIED":"Had the moisture removed","DRIFT":"Float aimlessly","DRINK":"Beverage","DRIVE":"Take the wheel",
 "DROVE":"Took the wheel","DRUNK":"Worse for wear","DUSTY":"In need of a clean","DWELL":"Live somewhere",
 "EAGER":"Keen","EAGLE":"Bird of prey; or two under par","EARLY":"Before time","EARTH":"Our planet",
 "EIGHT":"Number after seven","ELBOW":"Arm's bend","EMPTY":"Containing nothing","ENEMY":"Foe",
 "ENJOY":"Take pleasure in","ENTER":"Go in","ENTRY":"Way in","EQUAL":"The same as","ERROR":"Mistake",
 "EVENT":"Happening","EVERY":"Each and all","EXACT":"Precise","EXTRA":"Additional","FAINT":"Pass out",
 "FAITH":"Belief","FALSE":"Not true","FANCY":"Elaborate; or take a liking to","FATAL":"Deadly",
 "FAULT":"Flaw; or blame","FAVOUR":"","FEAST":"Grand meal","FENCE":"Garden boundary","FERRY":"Boat that crosses",
 "FEVER":"High temperature","FIELD":"Grassy expanse","FIERY":"Blazing","FIFTH":"After fourth",
 "FIGHT":"Come to blows","FINAL":"Last","FIRST":"Before all others","FIXED":"Repaired; or unmoving",
 "FLAME":"Fire's tongue","FLASH":"Sudden burst of light","FLEET":"Group of ships","FLESH":"Meat on the bone",
 "FLOAT":"Stay on the surface","FLOOD":"Overflow of water","FLOOR":"What you stand on","FLOUR":"Baking powder base",
 "FLUID":"Liquid","FLUTE":"Woodwind instrument","FOCUS":"Sharpen your attention","FORCE":"Strength",
 "FORTH":"Onward; a Scottish firth","FORTY":"Four tens","FOUND":"Located","FRAME":"What holds a picture",
 "FRANK":"Blunt and honest","FRAUD":"Deception","FRESH":"Newly made","FRONT":"Opposite of back",
 "FROST":"Icy morning coating","FROWN":"Unhappy expression","FRUIT":"Apple or pear","FULLY":"Completely",
 "FUNNY":"Amusing","GIANT":"Huge","GIVEN":"Handed over","GLASS":"Window material","GLOBE":"World in miniature",
 "GLORY":"Great renown","GOOSE":"Honking bird","GRACE":"Elegance","GRADE":"Mark out of ten",
 "GRAIN":"Wheat or rice","GRAND":"Magnificent; or a thousand","GRANT":"Bestow; or funding",
 "GRAPE":"Wine fruit","GRASP":"Grip","GRASS":"Lawn covering","GRAVE":"Serious; or a burial plot",
 "GREAT":"Excellent","GREED":"Wanting far too much","GREEN":"Colour of grass","GREET":"Say hello to",
 "GRIEF":"Deep sorrow","GRILL":"Cook under heat","GROSS":"Disgusting; or before deductions",
 "GROUP":"Collection of people","GROWN":"Fully developed","GUARD":"Protect","GUESS":"Estimate",
 "GUEST":"Visitor","GUIDE":"Show the way","GUILT":"Feeling of having done wrong","HABIT":"Routine behaviour",
 "HAPPY":"Cheerful","HARSH":"Severe","HASTE":"Undue speed","HATCH":"Emerge from an egg","HEARD":"Listened to",
 "HEART":"Ticker","HEAVY":"Weighing a lot","HEDGE":"Garden boundary of shrubs","HELLO":"Greeting",
 "HENCE":"Therefore","HOBBY":"Pastime","HONEY":"Bee's product","HORSE":"Grand National runner",
 "HOTEL":"Place to stay","HOUSE":"Home","HUMAN":"One of us","HUMID":"Muggy","HURRY":"Get a move on",
 "IDEAL":"Perfect","IMAGE":"Picture","INDEX":"Book's back-page guide","INNER":"Further in",
 "INPUT":"Data you feed in","IRONY":"Saying the opposite","ISSUE":"Problem; or a magazine edition",
 "IVORY":"Elephant tusk material","JELLY":"Wobbly pudding","JEWEL":"Precious stone","JOINT":"Sunday roast; or a knuckle",
 "JUDGE":"One in a wig and gown","JUICE":"Squeezed drink","KNEEL":"Go down on one knee","KNIFE":"Cutlery for cutting",
 "KNOCK":"Rap on the door","KNOWN":"Familiar to all","LABEL":"Sticker with the name","LARGE":"Big",
 "LASER":"Focused light beam","LATER":"Afterwards","LAUGH":"Chuckle","LAYER":"One level of many",
 "LEARN":"Take in knowledge","LEASE":"Rental agreement","LEAST":"Smallest amount","LEAVE":"Depart",
 "LEGAL":"Within the law","LEMON":"Sour yellow fruit","LEVEL":"Flat and even","LIGHT":"Not heavy; or illumination",
 "LIMIT":"Cap","LINEN":"Bed sheets fabric","LIVER":"Organ that filters","LOCAL":"Nearby; or the village pub",
 "LODGE":"Small house at the gate","LOGIC":"Sound reasoning","LOOSE":"Not tight","LORRY":"Big goods vehicle",
 "LOVER":"Sweetheart","LOWER":"Bring down","LOYAL":"Faithful","LUCKY":"Fortunate","LUNCH":"Midday meal",
 "MAGIC":"Sorcery","MAJOR":"Significant; or an army rank","MAKER":"One who creates","MARCH":"Month after February",
 "MATCH":"Football fixture; or a fire-starter","MAYBE":"Perhaps","MAYOR":"Town's first citizen",
 "MEDAL":"Olympic prize","MEDIA":"Press and TV","MERCY":"Compassion shown","MERGE":"Join into one",
 "MERIT":"Worthiness","METAL":"Iron or steel","METRE":"Hundred centimetres","MIGHT":"Power; or possibly",
 "MINOR":"Lesser","MINUS":"Subtraction sign","MIXED":"Blended","MODEL":"Miniature version",
 "MONEY":"Cash","MONTH":"Thirty days or so","MORAL":"Story's lesson","MOTOR":"Engine","MOUNT":"Climb onto",
 "MOUSE":"Cheese lover; or a clicker","MOUTH":"Where food goes in","MOVIE":"Film","MUSIC":"Organised sound",
 "NAKED":"Wearing nothing","NASTY":"Unpleasant","NAVAL":"To do with the fleet","NERVE":"Cheek; or a body signal",
 "NEVER":"Not once","NEWLY":"Recently","NIGHT":"After dark","NOBLE":"High-born","NOISE":"Unwanted sound",
 "NORTH":"Up on the map","NOTED":"Well known","NOVEL":"Book; or brand new","NURSE":"Ward carer",
 "OCCUR":"Happen","OCEAN":"Vast sea","OFFER":"Put forward","OFTEN":"Frequently","OLIVE":"Martini garnish",
 "ONION":"Layered bulb that makes you cry","ORDER":"Command; or tidiness","ORGAN":"Church instrument; or a body part",
 "OTHER":"The alternative","OUGHT":"Should","OUNCE":"Sixteenth of a pound","OUTER":"Further out",
 "OWNER":"One who possesses","PAINT":"Decorator's tin","PANEL":"Flat board; or a discussion group",
 "PANIC":"Sudden terror","PAPER":"What newspapers are printed on","PARTY":"Celebration; or a political group",
 "PASTA":"Italian staple","PATCH":"Mend a hole","PAUSE":"Brief stop","PEACE":"Absence of war",
 "PEACH":"Fuzzy stone fruit","PEARL":"Oyster's gem","PEDAL":"Foot lever","PENNY":"Smallest coin",
 "PHASE":"Stage of the moon","PHONE":"Ring someone","PHOTO":"Snap","PIANO":"88-key instrument",
 "PIECE":"Portion","PILOT":"One who flies the plane","PITCH":"Football ground; or throw",
 "PIZZA":"Sliced Italian round","PLACE":"Location","PLAIN":"Simple; or a flat expanse","PLANE":"Aircraft",
 "PLANT":"Green growing thing","PLATE":"Dinner dish","POINT":"Sharp end; or a score","POUND":"Sterling",
 "POWER":"Might","PRESS":"Push; or the newspapers","PRICE":"What it costs","PRIDE":"Lions' group; or self-respect",
 "PRIME":"Best; or a number like 7","PRINT":"Put on paper","PRIZE":"Award for winning","PROOF":"Evidence",
 "PROUD":"Pleased with yourself","PROVE":"Demonstrate as true","PUPIL":"Schoolchild; or eye's centre",
 "PURSE":"Where coins live","QUEEN":"Monarch; or a chess piece","QUEST":"Long search","QUEUE":"British pastime: waiting in line",
 "QUICK":"Fast","QUIET":"Making no noise","QUITE":"Fairly","RADIO":"Wireless","RAISE":"Lift up",
 "RANCH":"Cattle farm","RANGE":"Spread; or a mountain chain","RAPID":"Very quick","RATIO":"Proportion",
 "REACH":"Stretch to get","REACT":"Respond","READY":"Prepared","REALM":"Kingdom","REBEL":"One who revolts",
 "REFER":"Point towards","REIGN":"Monarch's time on the throne","RELAX":"Unwind","RELAY":"Team race",
 "REPLY":"Answer","RIDGE":"Long crest","RIGHT":"Correct","RIVAL":"Competitor","RIVER":"Thames or Severn",
 "ROAST":"Sunday dinner","ROBOT":"Mechanical worker","ROMAN":"Ancient conqueror of Britain","ROUGH":"Not smooth",
 "ROUND":"Circular; or a pub order","ROUTE":"Way to go","ROYAL":"To do with the crown","RUGBY":"Sport with an oval ball",
 "RULER":"One who governs; or a measuring stick","RURAL":"Of the countryside","SAINT":"Canonised one",
 "SALAD":"Bowl of leaves","SAUCE":"Gravy's cousin","SCALE":"Measuring range; or fish covering",
 "SCARF":"Neck warmer","SCENE":"Part of a play","SCENT":"Perfume","SCORE":"Goals tally; or twenty",
 "SCOUT":"One prepared","SENSE":"Sight or smell","SERVE":"Wait on; or start a tennis point",
 "SEVEN":"Days in a week","SHADE":"Out of the sun","SHAKE":"Wobble","SHAME":"Disgrace","SHAPE":"Form",
 "SHARE":"Divide between","SHARK":"Finned predator","SHARP":"Keen-edged","SHEEP":"Woolly flock member",
 "SHEET":"Bed linen; or of paper","SHELF":"Where books sit","SHELL":"Beach find","SHIFT":"Work period; or move",
 "SHINE":"Gleam","SHIRT":"Buttoned top","SHOCK":"Nasty surprise","SHOOT":"Fire a gun; or a new plant growth",
 "SHORE":"Coastline","SHORT":"Not tall","SHOUT":"Yell","SHOWN":"Displayed","SIGHT":"Vision",
 "SILLY":"Foolish","SINCE":"From then on","SIXTH":"After fifth","SIXTY":"Minutes in an hour",
 "SKILL":"Ability","SLEEP":"Forty winks","SLICE":"Cut a piece off","SLIDE":"Playground chute",
 "SMALL":"Little","SMART":"Clever; or well dressed","SMELL":"Odour","SMILE":"Turn up the corners",
 "SMOKE":"What comes off a fire","SNAKE":"Legless slitherer","SOLAR":"Of the sun","SOLID":"Not liquid or gas",
 "SOLVE":"Work out the answer","SORRY":"Word of apology","SOUND":"What you hear","SOUTH":"Down on the map",
 "SPACE":"Final frontier","SPARE":"Extra; or the fifth wheel","SPEAK":"Talk","SPEED":"Rate of travel",
 "SPELL":"Magic words; or write letters in order","SPEND":"Part with money","SPICE":"Curry flavouring",
 "SPINE":"Backbone","SPLIT":"Divide","SPOKE":"Talked; or a wheel's bar","SPOON":"Cutlery for soup",
 "SPORT":"Football or cricket","SPRAY":"Fine mist","SQUAD":"Team's full roster","STAFF":"Employees",
 "STAGE":"Where a play happens","STAIN":"Stubborn mark","STAIR":"One step of many","STAKE":"What you wager",
 "STAMP":"Letter's corner sticker","STAND":"Get to your feet","STARE":"Look fixedly","START":"Begin",
 "STATE":"Condition; or a country","STEAL":"Take unlawfully","STEAM":"Boiling kettle's output",
 "STEEL":"Sheffield's metal","STEEP":"Sharply sloping","STEER":"Guide the wheel","STICK":"Branch; or adhere",
 "STILL":"Motionless; or even now","STOCK":"Soup base; or shares","STONE":"Rock; or fourteen pounds",
 "STOOD":"Was on its feet","STORE":"Shop","STORM":"Thunder and lightning","STORY":"Tale","STOUT":"Guinness, e.g.",
 "STOVE":"Cooker","STRIP":"Narrow band; or a team's kit","STUCK":"Unable to move","STUDY":"Revise",
 "STYLE":"Manner; or flair","SUGAR":"Sweetener","SUITE":"Set of rooms","SUNNY":"Cloudless",
 "SUPER":"Excellent","SWEET":"Sugary","SWIFT":"Fast; or a summer bird","SWING":"Playground seat on chains",
 "SWORD":"Blade for duelling","TABLE":"Where you eat","TASTE":"Flavour","TEACH":"Instruct",
 "TEETH":"What you brush","TENTH":"After ninth","THANK":"Express gratitude","THEFT":"Stealing",
 "THEIR":"Belonging to them","THEME":"Recurring subject","THERE":"In that place","THICK":"Not thin",
 "THIEF":"One who steals","THING":"Object","THINK":"Use your head","THIRD":"After second",
 "THREE":"Number after two","THROW":"Hurl","THUMB":"Opposable digit","TIGER":"Striped big cat",
 "TIGHT":"Not loose","TIRED":"In need of sleep","TITLE":"Book's name","TOAST":"Grilled bread; or a tribute",
 "TODAY":"This very day","TOOTH":"Dentist's concern","TOPIC":"Subject","TOTAL":"Sum",
 "TOUCH":"Feel","TOUGH":"Hard-wearing","TOWEL":"What you dry with","TOWER":"Tall structure",
 "TRACK":"Railway line; or a song","TRADE":"Buying and selling","TRAIL":"Path","TRAIN":"Rail service",
 "TREAT":"Something nice","TREND":"Prevailing fashion","TRIAL":"Court hearing; or a test",
 "TRIBE":"Group with shared ancestry","TRICK":"Sly ploy","TRIED":"Attempted","TRUCK":"Lorry",
 "TRULY":"Genuinely","TRUNK":"Elephant's nose; or a tree's stem","TRUST":"Have faith in","TRUTH":"What is so",
 "TUDOR":"Henry VIII's dynasty","TWICE":"Two times","TWIST":"Turn sharply","UNCLE":"Parent's brother",
 "UNDER":"Beneath","UNION":"Joining together","UNITE":"Bring together","UNTIL":"Up to the time that",
 "UPPER":"Higher","UPSET":"Distressed","URBAN":"Of the town","USUAL":"Customary","VAGUE":"Unclear",
 "VALID":"Legitimate","VALUE":"Worth","VENUE":"Where an event is held","VERSE":"Poem's stanza",
 "VIDEO":"Moving footage","VILLA":"Holiday house","VIRUS":"Bug that spreads","VISIT":"Call on",
 "VITAL":"Absolutely essential","VOICE":"What you speak with","VOTED":"Cast a ballot","WAGON":"Cart",
 "WAIST":"Where the belt goes","WATCH":"Wrist timepiece; or observe","WATER":"H2O","WHALE":"Ocean giant",
 "WHEAT":"Bread grain","WHEEL":"Round roller","WHERE":"In what place","WHICH":"What one",
 "WHILE":"During the time that","WHITE":"Colour of snow","WHOLE":"Entire","WOMAN":"Adult female",
 "WORLD":"The globe","WORRY":"Fret","WORSE":"Less good","WORTH":"Value","WOULD":"Auxiliary of the conditional",
 "WOUND":"Injury","WRECK":"Ruin","WRIST":"Where the watch goes","WRITE":"Put pen to paper",
 "WRONG":"Incorrect","YIELD":"Give way","YOUNG":"Not old","YOUTH":"Young person",
}
W4 = {
 "ABLE":"Capable","ACHE":"Dull pain","ACID":"Vinegar is one","ACRE":"Field measure","AGED":"Grown old",
 "AIDE":"Assistant","AJAR":"Slightly open","AREA":"Region","ARMY":"Soldiers en masse","AUNT":"Parent's sister",
 "AXLE":"Wheel's rod","BAKE":"Put in the oven","BALD":"Hairless","BALL":"Round plaything","BAND":"Musical group",
 "BANK":"Where money sits","BARE":"Uncovered","BARN":"Farm building","BASE":"Foundation","BATH":"Somerset spa city; or a soak",
 "BEAM":"Ray of light","BEAN":"Heinz tinful","BEAR":"Woodland growler","BEAT":"Rhythm","BEEF":"Sunday roast meat",
 "BELL":"It tolls","BELT":"Trouser holder","BEND":"Curve","BEST":"Top of the lot","BIKE":"Two-wheeler",
 "BILL":"What's owed","BIRD":"Feathered flier","BITE":"Nip","BLOW":"Strike; or exhale","BLUE":"Colour of the sky",
 "BOAT":"Small vessel","BOLD":"Daring","BOLT":"Fastener; or dash off","BOMB":"Explosive","BOND":"Tie; or 007",
 "BONE":"Skeleton part","BOOK":"Bound pages","BOOT":"Car's back; or footwear","BORE":"Tedious sort",
 "BORN":"Brought into the world","BOTH":"The two","BOWL":"Deep dish","CAFE":"Coffee stop","CAGE":"Bird's home",
 "CAKE":"Birthday bake","CALF":"Young cow","CALL":"Ring up","CALM":"Serene","CAMP":"Tent site","CANE":"Walking stick",
 "CARD":"Birthday greeting","CARE":"Look after","CART":"Horse-drawn wagon","CASE":"Instance; or a suitcase",
 "CASH":"Notes and coins","CAST":"Play's actors","CAVE":"Underground hollow","CELL":"Prison room; or a body's unit",
 "CHAT":"Natter","CHEF":"Kitchen boss","CHIP":"Fish's partner","CITY":"Large town","CLAY":"Potter's material",
 "CLIP":"Fasten; or a short video","CLUB":"Society; or a golf stick","CLUE":"Hint","COAL":"Fossil fuel lump",
 "COAT":"Outer garment","CODE":"Secret writing","COIN":"Piece of money","COLD":"Chilly","COOK":"Prepare food",
 "COOL":"Mildly cold","COPE":"Manage","COPY":"Duplicate","CORD":"Length of string","CORE":"Apple's centre",
 "CORK":"Bottle stopper","CORN":"Maize","COST":"Price","CROP":"Harvest","CUBE":"Six-sided solid",
 "CURE":"Remedy","DARE":"Challenge","DARK":"Without light","DATA":"Information","DATE":"Calendar day",
 "DAWN":"Break of day","DEAD":"No longer living","DEAF":"Unable to hear","DEAL":"Agreement","DEAR":"Beloved; or costly",
 "DEBT":"What you owe","DECK":"Ship's floor; or of cards","DEEP":"Far down","DEER":"Antlered woodland animal",
 "DENY":"Refuse to admit","DESK":"Where you work","DIAL":"Clock's face","DICE":"Cubes you roll",
 "DIET":"Eating regime","DIRT":"Soil","DISC":"Round flat object","DISH":"Plate; or a recipe","DIVE":"Plunge in",
 "DOCK":"Where ships tie up","DOOR":"Way in","DOSE":"Amount of medicine","DOVE":"Peace bird",
 "DRAW":"Sketch; or a tie","DREW":"Sketched","DROP":"Let fall","DRUM":"Percussion","DUCK":"Quacker; or nought in cricket",
 "DUKE":"Highest noble rank","DULL":"Boring","DUST":"Surface grime","DUTY":"Obligation","EACH":"Every one",
 "EARL":"Noble below a marquess","EARN":"Work for pay","EASE":"Lack of difficulty","EAST":"Right on the map",
 "EASY":"Not hard","ECHO":"Sound bouncing back","EDGE":"Border","EDIT":"Revise","EPIC":"Grand in scale",
 "EVEN":"Level; or divisible by two","EVIL":"Wicked","EXAM":"School test","EXIT":"Way out","FACE":"Front of the head",
 "FACT":"Something true","FADE":"Grow dim","FAIL":"Not succeed","FAIR":"Just; or a funfair","FAKE":"Counterfeit",
 "FALL":"Tumble","FARM":"Where crops grow","FAST":"Quick","FATE":"Destiny","FEAR":"Dread","FEAT":"Impressive deed",
 "FEED":"Give food to","FEEL":"Sense by touch","FELL":"Dropped; or a northern hill","FERN":"Shade-loving plant",
 "FILE":"Document; or a rasp","FILL":"Make full","FILM":"Movie","FIND":"Discover","FINE":"Penalty; or all right",
 "FIRE":"Flames","FIRM":"Company; or solid","FISH":"Cod or haddock","FIST":"Clenched hand","FLAG":"Union Jack, e.g.",
 "FLAT":"Level; or an apartment","FLEE":"Run away","FLEW":"Took to the air","FLIP":"Turn over","FLOW":"Stream along",
 "FOAM":"Froth","FOLD":"Bend over","FOLK":"People","FOOD":"Nourishment","FOOL":"Idiot","FOOT":"Twelve inches",
 "FORD":"River crossing; or a car maker","FORK":"Cutlery prong","FORM":"Shape; or a document","FORT":"Stronghold",
 "FOUL":"Football offence","FOUR":"Number after three","FREE":"At no cost","FROG":"Pond hopper",
 "FROM":"Starting at","FUEL":"What powers an engine","FULL":"Holding all it can","FUND":"Money set aside",
 "GAME":"Match","GATE":"Garden entrance","GAVE":"Handed over","GEAR":"Equipment","GENE":"Unit of heredity",
 "GIFT":"Present","GIRL":"Young female","GIVE":"Hand over","GLAD":"Pleased","GLOW":"Soft light",
 "GLUE":"Sticky stuff","GOAL":"Net-buster","GOAT":"Bearded climber","GOLD":"Precious yellow metal",
 "GOLF":"Links game","GONE":"Departed","GOOD":"Not bad","GOWN":"Long dress","GRAB":"Snatch","GRAY":"Colourless shade",
 "GREW":"Got bigger","GRIM":"Bleak","GRIN":"Broad smile","GRIP":"Firm hold","GROW":"Get bigger",
 "GULF":"Large bay","HAIR":"What's on your head","HALF":"Fifty per cent","HALL":"Entrance room",
 "HAND":"End of the arm","HANG":"Suspend","HARD":"Not easy","HARM":"Damage","HATE":"Loathe","HAVE":"Possess",
 "HAWK":"Bird of prey","HEAD":"Top of the body","HEAL":"Make well","HEAP":"Pile","HEAR":"Listen to",
 "HEAT":"Warmth","HEEL":"Back of the foot","HELD":"Grasped","HELL":"The other place","HELP":"Assist",
 "HERB":"Kitchen seasoning plant","HERD":"Group of cattle","HERO":"Brave one","HIDE":"Conceal",
 "HIGH":"Far up","HILL":"Small rise","HINT":"Clue","HIRE":"Rent","HOLD":"Grasp","HOLE":"Opening",
 "HOME":"Where the heart is","HOOD":"Coat's head cover","HOOK":"Bent catcher","HOPE":"Wish for",
 "HORN":"Bull's weapon; or a car's honker","HOST":"One who entertains","HOUR":"Sixty minutes",
 "HUGE":"Enormous","HUNT":"Search for prey","HURT":"Cause pain","ICON":"Symbol on a screen",
 "IDEA":"Bright thought","IDLE":"Doing nothing","INCH":"2.54 centimetres","INTO":"To the inside of",
 "IRON":"Metal; or press clothes","ITEM":"Single thing","JAZZ":"Improvised music","JOKE":"Gag",
 "JUMP":"Leap","JURY":"Twelve good citizens","JUST":"Merely; or fair","KEEN":"Eager","KEEP":"Retain",
 "KERB":"Pavement edge","KICK":"Boot","KIND":"Considerate; or a type","KING":"Monarch","KISS":"Peck",
 "KNEE":"Leg joint","KNEW":"Was aware of","KNOT":"Tied loop","LACK":"Be without","LADY":"Woman of rank",
 "LAKE":"Inland water","LAMB":"Young sheep","LAMP":"Light source","LAND":"Terra firma","LANE":"Narrow road",
 "LAST":"Final","LATE":"After time","LAWN":"Mown grass","LAZY":"Idle","LEAD":"Go first; or a heavy metal",
 "LEAF":"Tree's green blade","LEAN":"Tilt; or without fat","LEAP":"Jump","LEFT":"Not right","LEND":"Loan out",
 "LENS":"Camera's glass","LESS":"Not as much","LIAR":"One who fibs","LIFE":"Existence","LIFT":"Elevator",
 "LIKE":"Be fond of","LIMB":"Arm or leg","LIME":"Green citrus","LINE":"Straight mark","LINK":"Connection",
 "LION":"King of beasts","LIST":"Itemised roll","LIVE":"Be alive; or broadcast now","LOAD":"Burden",
 "LOAN":"Money lent","LOCK":"Key's partner","LOFT":"Attic","LONG":"Not short","LOOK":"Glance",
 "LOOP":"Closed curve","LORD":"Peer of the realm","LOSE":"Mislay","LOST":"Mislaid","LOUD":"Noisy",
 "LOVE":"Adore; or nil in tennis","LUCK":"Fortune","LUNG":"Breathing organ","MAIL":"Post","MAIN":"Chief",
 "MAKE":"Create","MALE":"Man or boy","MALL":"Shopping centre","MANY":"Numerous","MARK":"Stain; or a score",
 "MASK":"Face cover","MAST":"Ship's pole","MATE":"Chum","MATH":"Sums, to an American","MEAL":"Sitting of food",
 "MEAN":"Signify; or unkind","MEAT":"Butcher's wares","MEET":"Come together","MELT":"Turn to liquid",
 "MEND":"Repair","MENU":"List of dishes","MILD":"Gentle","MILE":"1,760 yards","MILK":"Dairy drink",
 "MILL":"Where grain is ground","MIND":"Brain's workings","MINE":"Belongs to me; or a pit","MINT":"Herb; or where coins are made",
 "MISS":"Fail to hit","MIST":"Light fog","MOCK":"Ridicule","MODE":"Manner","MOOD":"State of mind",
 "MOON":"Night's light","MORE":"Additional","MOSS":"Damp green growth","MOST":"The greatest amount",
 "MOTH":"Lamp-drawn flutterer","MOVE":"Shift","MUCH":"A lot","MULE":"Donkey's hybrid","NAIL":"Hammer's target",
 "NAME":"What you're called","NAVY":"Senior service","NEAR":"Close by","NEAT":"Tidy","NECK":"Head's support",
 "NEED":"Require","NEST":"Bird's home","NEWS":"Current events","NEXT":"Following","NICE":"Pleasant",
 "NINE":"Number after eight","NODE":"Junction point","NONE":"Not any","NOON":"Midday","NORM":"The usual",
 "NOSE":"Smeller","NOTE":"Jotting; or a tenner","NOUN":"Naming word","OATH":"Solemn promise","OBEY":"Do as told",
 "ODDS":"Bookmaker's numbers","ONCE":"One time","ONLY":"Solely","ONTO":"Upon","OPEN":"Not shut",
 "ORAL":"Spoken","OVAL":"Egg-shaped; or a London cricket ground","OVEN":"Where you bake","OVER":"Finished; or six balls",
 "PACE":"Speed of walking","PACK":"Fill a case","PAGE":"Sheet of a book","PAID":"Settled up","PAIN":"Ache",
 "PAIR":"Two of a kind","PALE":"Washed out","PALM":"Hand's inside; or a tropical tree","PARK":"Green space",
 "PART":"Portion","PASS":"Go by","PAST":"Time gone by","PATH":"Walkway","PEAK":"Summit","PEAR":"Fruit shaped like a teardrop",
 "PEAT":"Bog fuel","PILE":"Heap","PINE":"Evergreen; or yearn","PINK":"Pale red","PINT":"Pub measure",
 "PIPE":"Tube","PLAN":"Scheme","PLAY":"Have fun; or a drama","PLOT":"Story's thread; or a scheme",
 "PLUG":"Socket's partner","PLUS":"Addition sign","POEM":"Verse","POET":"Verse writer","POLE":"Long rod; or the Arctic",
 "POLL":"Vote count","POND":"Small still water","POOL":"Swimming spot","POOR":"Hard up","PORT":"Harbour; or a fortified wine",
 "POSE":"Strike an attitude","POST":"Mail; or a stake","POUR":"Tip out","PRAY":"Address a deity",
 "PREY":"Hunted animal","PULL":"Tug","PUMP":"Move fluid","PURE":"Unmixed","PUSH":"Shove","QUIT":"Give up",
 "RACE":"Contest of speed","RAGE":"Fury","RAIL":"Train track","RAIN":"British weather","RANK":"Position in order",
 "RARE":"Uncommon","RATE":"Speed; or a charge","READ":"Take in text","REAL":"Genuine","RELY":"Depend",
 "RENT":"Landlord's due","REST":"Take a break","RICE":"Curry's companion","RICH":"Wealthy","RIDE":"Travel on",
 "RING":"Circle; or telephone","RIPE":"Ready to eat","RISE":"Go up","RISK":"Chance of loss","ROAD":"Highway",
 "ROAR":"Lion's cry","ROCK":"Stone; or a music genre","ROLE":"Part played","ROLL":"Turn over; or a bread bun",
 "ROOF":"House's top","ROOM":"Space","ROOT":"Underground part","ROPE":"Thick cord","ROSE":"Thorny bloom",
 "RUDE":"Impolite","RUIN":"Wreck","RULE":"Regulation","RUSH":"Hurry","RUST":"Iron's orange decay",
 "SAFE":"Out of danger","SAID":"Uttered","SAIL":"Boat's canvas","SALE":"Bargain time","SALT":"Pepper's partner",
 "SAME":"Identical","SAND":"Beach grains","SAVE":"Rescue; or put by","SCAR":"Wound's mark","SEAL":"Close tight; or a barking sea mammal",
 "SEAT":"Chair","SEED":"What you sow","SEEK":"Look for","SEEM":"Appear","SEEN":"Observed","SELF":"One's own person",
 "SELL":"Trade for money","SEND":"Dispatch","SHED":"Garden hut","SHIP":"Sea vessel","SHOE":"Foot's wear",
 "SHOP":"Where you buy","SHOT":"Attempt; or a bullet","SHOW":"Display","SHUT":"Close","SICK":"Unwell",
 "SIDE":"Flank","SIGN":"Notice board","SILK":"Smooth fabric","SING":"Carry a tune","SINK":"Go under; or a basin",
 "SITE":"Location","SIZE":"Dimensions","SKIN":"Body's covering","SKIP":"Hop along; or a rubbish container",
 "SLAB":"Thick flat piece","SLIM":"Slender","SLIP":"Lose your footing","SLOW":"Not fast","SNAP":"Break sharply; or a photo",
 "SNOW":"Winter fall","SOAP":"Washing bar","SOFA":"Settee","SOFT":"Not hard","SOIL":"Earth","SOLD":"Traded away",
 "SOLE":"Only; or a flatfish","SONG":"Tune with words","SOON":"Before long","SORT":"Arrange; or a type",
 "SOUL":"Spirit","SOUP":"Starter in a bowl","SOUR":"Sharp-tasting","SPIN":"Rotate","SPOT":"Dot; or notice",
 "STAR":"Night sky twinkler","STAY":"Remain","STEM":"Plant's stalk","STEP":"Pace","STIR":"Mix with a spoon",
 "STOP":"Halt","SUCH":"Of that kind","SUIT":"Two-piece outfit","SURE":"Certain","SWAP":"Exchange",
 "SWIM":"Move through water","TAIL":"Rear end","TAKE":"Grab","TALE":"Story","TALK":"Speak","TALL":"Of great height",
 "TANK":"Water container; or an armoured vehicle","TAPE":"Sticky strip","TASK":"Job to do","TEAM":"Side",
 "TEAR":"Rip; or an eye's drop","TELL":"Inform","TEND":"Look after","TENT":"Camper's shelter","TERM":"School period",
 "TEST":"Exam","TEXT":"Written words","THAN":"Comparison word","THAT":"The other one","THAW":"Melt after a freeze",
 "THEM":"Those people","THEN":"At that time","THEY":"Those folk","THIN":"Not thick","THIS":"The near one",
 "THUS":"In this way","TIDE":"Sea's rise and fall","TIDY":"Neat","TILE":"Roof or floor square","TIME":"What clocks tell",
 "TINY":"Very small","TIRE":"Grow weary","TOAD":"Warty hopper","TOLD":"Informed","TOLL":"Bridge charge",
 "TONE":"Quality of sound","TOOK":"Grabbed","TOOL":"Implement","TORN":"Ripped","TOUR":"Trip around",
 "TOWN":"Bigger than a village","TRAP":"Snare","TRAY":"Serving board","TREE":"Oak or ash","TRIM":"Cut neatly",
 "TRIP":"Journey; or stumble","TRUE":"Not false","TUBE":"London Underground","TUNE":"Melody","TURN":"Rotate",
 "TWIG":"Small branch","TWIN":"One of two born together","TYPE":"Sort; or key in","UGLY":"Not easy on the eye",
 "UNIT":"Single measure","UPON":"On top of","URGE":"Strong impulse","USED":"Second-hand","USER":"One who uses",
 "VAIN":"Conceited","VAST":"Enormous","VEIL":"Face covering","VERB":"Doing word","VERY":"Extremely",
 "VIEW":"What you can see","VOTE":"Cast a ballot","WAGE":"Weekly pay","WAIT":"Hang on","WAKE":"Stop sleeping",
 "WALK":"Go on foot","WALL":"Brick divider","WANT":"Desire","WARD":"Hospital room","WARM":"Pleasantly hot",
 "WARN":"Alert to danger","WASH":"Clean with water","WASP":"Stinging picnic pest","WAVE":"Sea's swell; or greet",
 "WEAK":"Feeble","WEAR":"Have on","WEED":"Garden intruder","WEEK":"Seven days","WELL":"Water source; or in good health",
 "WENT":"Departed","WERE":"Past of are","WEST":"Left on the map","WHAT":"Which thing","WHEN":"At what time",
 "WHIP":"Lash","WIDE":"Broad","WIFE":"Married woman","WILD":"Untamed","WILL":"Testament; or shall",
 "WIND":"Breeze","WINE":"Grape drink","WING":"Bird's flier","WIPE":"Rub clean","WIRE":"Metal thread",
 "WISE":"Sagacious","WISH":"Desire","WOKE":"Stopped sleeping","WOLF":"Pack hunter","WOOD":"Timber",
 "WOOL":"Sheep's coat","WORD":"Unit of speech","WORE":"Had on","WORK":"Toil","WORM":"Soil wriggler",
 "YARD":"Three feet","YEAR":"365 days","YOUR":"Belonging to you","ZERO":"Nought","ZONE":"Area",
}
W3 = {
 "ACE":"Card above king","ACT":"Deed; or a play's part","ADD":"Sum up","AGE":"Years lived","AGO":"In the past",
 "AID":"Help","AIM":"Target","AIR":"What we breathe","ALE":"Pint of bitter","ALL":"Every one",
 "AND":"Plus","ANT":"Colony insect","ANY":"Some at all","APE":"Gorilla or chimp","ARC":"Curved line",
 "ARM":"Shoulder to hand","ART":"Gallery contents","ASH":"Fire's leavings; or a tree","ASK":"Enquire",
 "ATE":"Consumed","AWE":"Wonder","AXE":"Chopper","BAD":"Not good","BAG":"Carrier","BAN":"Forbid",
 "BAR":"Pub counter","BAT":"Cricket willow; or a night flier","BAY":"Coastal curve","BED":"Where you sleep",
 "BEE":"Honey maker","BEG":"Plead","BET":"Wager","BID":"Auction offer","BIG":"Large","BIN":"Rubbish holder",
 "BIT":"Small piece","BOG":"Marsh","BOW":"Bend forward; or an archer's weapon","BOX":"Cardboard container",
 "BOY":"Young lad","BUD":"Flower to be","BUG":"Insect; or a glitch","BUN":"Bakery roll","BUS":"Public transport",
 "BUT":"However","BUY":"Purchase","CAB":"Taxi","CAN":"Tin; or be able","CAP":"Hat","CAR":"Motor",
 "CAT":"Mouser","COD":"Fish and chips fish","COG":"Gear's tooth","CON":"Trick","COT":"Baby's bed",
 "COW":"Milk provider","CRY":"Weep","CUB":"Young bear","CUE":"Snooker stick","CUP":"FA trophy; or a mug",
 "CUT":"Slice","DAB":"Light touch","DAD":"Father","DAM":"Water barrier","DAY":"24 hours","DEN":"Animal's lair",
 "DEW":"Morning moisture","DID":"Performed","DIE":"Expire","DIG":"Excavate","DIM":"Not bright","DIP":"Brief plunge",
 "DOG":"Man's best friend","DOT":"Small point","DRY":"Not wet","DUE":"Owed","DUG":"Excavated","DYE":"Colouring agent",
 "EAR":"Hearing organ","EAT":"Consume","EEL":"Snaky fish","EGG":"Breakfast oval","EGO":"Sense of self",
 "ELF":"Pointy-eared sprite","ELM":"Tall tree","END":"Finish","ERA":"Age","EVE":"Night before","EWE":"Female sheep",
 "EYE":"Seer","FAN":"Supporter; or a cooler","FAR":"Distant","FAT":"Not lean","FEE":"Charge","FEW":"Not many",
 "FIG":"Newton's biscuit fruit","FIT":"In good shape","FIX":"Repair","FLY":"Take to the air","FOG":"Thick mist",
 "FOR":"In favour of","FOX":"Cunning one","FRY":"Cook in oil","FUN":"Enjoyment","FUR":"Animal coat",
 "GAP":"Opening","GAS":"Not solid or liquid","GEM":"Precious stone","GET":"Obtain","GIN":"Tonic's partner",
 "GOD":"Deity","GOT":"Obtained","GUM":"Chew; or tooth's bed","GUN":"Firearm","GUT":"Belly","GUY":"Bloke",
 "HAD":"Possessed","HAM":"Sandwich filler","HAS":"Owns","HAT":"Head cover","HAY":"Dried grass","HEN":"Egg layer",
 "HER":"Belonging to she","HID":"Concealed","HIM":"That man","HIP":"Side joint","HIS":"Belonging to he",
 "HIT":"Strike","HOG":"Pig","HOP":"Small jump; or a beer flavouring","HOT":"High temperature","HOW":"In what way",
 "HUB":"Wheel's centre","HUG":"Embrace","HUT":"Small shelter","ICE":"Frozen water","ILL":"Unwell",
 "INK":"Pen's fluid","INN":"Village pub","ION":"Charged particle","ITS":"Belonging to it","JAB":"Quick poke; or a vaccine",
 "JAM":"Toast spread; or a traffic snarl","JAR":"Glass container","JAW":"Chin's hinge","JET":"Fast plane",
 "JOB":"Employment","JOG":"Gentle run","JOY":"Delight","JUG":"Pouring vessel","KEY":"Lock opener",
 "KID":"Child; or a young goat","KIT":"Equipment; or a team's strip","LAB":"Science room","LAD":"Young man",
 "LAP":"Circuit; or where you sit","LAW":"Statute","LAY":"Put down","LEG":"Limb for walking","LET":"Allow",
 "LID":"Cover","LIE":"Untruth","LIP":"Mouth's edge","LIT":"Illuminated","LOG":"Fallen timber","LOT":"A great deal",
 "LOW":"Not high","MAD":"Insane","MAN":"Adult male","MAP":"Guide to the roads","MAT":"Doormat","MAY":"Month of blossom",
 "MEN":"Blokes","MET":"Encountered","MIX":"Blend","MUD":"Wet earth","MUG":"Cup with a handle","NET":"Goal's mesh",
 "NEW":"Not old","NIL":"Nothing","NOD":"Head's yes","NOR":"And not","NOT":"By no means","NOW":"At this moment",
 "NUT":"Bolt's partner","OAK":"Mighty tree","OAR":"Rowing blade","ODD":"Strange; or not even","OFF":"Not on",
 "OIL":"Engine lubricant","OLD":"Aged","ONE":"Single","OUR":"Belonging to us","OUT":"Not in","OWE":"Be in debt",
 "OWL":"Night hooter","OWN":"Possess","PAD":"Cushion","PAN":"Frying vessel","PAR":"Golf's standard",
 "PAT":"Gentle tap","PAW":"Animal's foot","PAY":"Settle up","PEA":"Green pod ball","PEG":"Washing line clip",
 "PEN":"Writing tool","PET":"Household animal","PIE":"Pastry dish","PIG":"Farmyard oinker","PIN":"Small spike",
 "PIT":"Hole; or a mine","PLY":"Layer of wood","POD":"Pea's case","POT":"Cooking vessel","PUB":"The local",
 "PUP":"Young dog","PUT":"Place","RAG":"Old cloth","RAM":"Male sheep","RAN":"Sprinted","RAT":"Rodent",
 "RAW":"Uncooked","RAY":"Beam of light","RED":"Colour of blood","RIB":"Chest bone","RID":"Free of",
 "RIM":"Outer edge","RIP":"Tear","ROB":"Steal from","ROD":"Slender bar","ROT":"Decay","ROW":"Line; or an argument",
 "RUB":"Apply friction","RUG":"Small carpet","RUM":"Pirate's drink","RUN":"Sprint","RYE":"Bread grain",
 "SAD":"Unhappy","SAG":"Droop","SAT":"Was seated","SAW":"Cutting tool; or observed","SAY":"Utter",
 "SEA":"The briny","SEE":"Perceive","SET":"Put in place","SEW":"Stitch","SHE":"That woman","SHY":"Bashful",
 "SIN":"Wrongdoing","SIP":"Small drink","SIR":"Knight's title","SIT":"Take a seat","SIX":"Half a dozen",
 "SKI":"Snow runner","SKY":"What's overhead","SLY":"Cunning","SOB":"Weep loudly","SON":"Male child",
 "SOW":"Plant seed","SPA":"Health resort","SPY":"Secret agent","SUB":"Replacement player","SUM":"Total",
 "SUN":"Our star","TAG":"Label","TAN":"Sun's colour","TAP":"Water's outlet","TAR":"Road's black stuff",
 "TAX":"Levy","TEA":"Cuppa","TEN":"Number after nine","THE":"Definite article","TIE":"Neckwear; or a draw",
 "TIN":"Can","TIP":"Gratuity; or an end","TOE":"Foot's digit","TON":"Heavy weight","TOO":"As well",
 "TOP":"Highest point","TOW":"Pull along","TOY":"Plaything","TRY":"Attempt; or a rugby score","TUB":"Large container",
 "TUG":"Sharp pull","TWO":"A pair","URN":"Ashes' vessel","USE":"Employ","VAN":"Delivery vehicle","VAT":"Big tub",
 "VET":"Animal doctor","VIA":"By way of","VOW":"Solemn promise","WAR":"Armed conflict","WAS":"Used to be",
 "WAX":"Candle material","WAY":"Route","WEB":"Spider's work","WED":"Marry","WET":"Soaked","WHO":"Which person",
 "WHY":"For what reason","WIG":"False hair","WIN":"Come first","WIT":"Quick humour","WOE":"Misery",
 "WON":"Came first","WOO":"Court","YES":"Affirmative","YET":"So far","YOU":"The reader","ZIP":"Fastener",
}
BANK = {}
for d in (W3, W4, W5):
    BANK.update({k: v for k, v in d.items() if v})
if __name__ == "__main__":
    from collections import Counter
    print("bank size:", len(BANK), dict(Counter(len(w) for w in BANK)))
